//=============================================================================
// DO NOT MODIFY THIS FILE MANUALLY!!
// THIS FILE IS GENERATED BY NETPROTO.
// IF YOU HAVE ANY QUESTIONS PLEASE CONTACT LUJIAN.
//=============================================================================

namespace Network.Messages
{
    public enum MessageType
    {
         MSG_Undefined = 0,
         //LS2User begin
         MSG_LS2U_LoginResult = 4461,
         MSG_Web2LS_Crypto = 9959,
         MSG_Web2LS_Normal = 11129,
         MSG_GS2U_ChangeLineResponse = 15641,
         MSG_LS2U_GameLineServerList = 17992,
         MSG_LS2U_LoginQue = 25241,
         MSG_U2LS_RequestGSLine = 39508,
         MSG_U2LS_Login_Normal = 41532,
         MSG_LS2Web_CryptoAck = 46746,
         MSG_LS2Web_NormalAck = 58400,
         //LS2User end
    }
    public partial class MessageFactory
    {
        static public void Initialize() {
            RegisterMessageId( MessageType.MSG_LS2U_LoginResult, LS2U_LoginResult.Create );
            RegisterMessageId( MessageType.MSG_GS2U_ChangeLineResponse, GS2U_ChangeLineResponse.Create );
            RegisterMessageId( MessageType.MSG_LS2U_GameLineServerList, LS2U_GameLineServerList.Create );
            RegisterMessageId( MessageType.MSG_LS2U_LoginQue, LS2U_LoginQue.Create );
            RegisterMessageId( MessageType.MSG_LS2Web_CryptoAck, LS2Web_CryptoAck.Create );
            RegisterMessageId( MessageType.MSG_LS2Web_NormalAck, LS2Web_NormalAck.Create );
        }
    }
}
//EOF
