DROP DATABASE IF EXISTS `3dgamedata`;
CREATE DATABASE `3dgamedata` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
DROP DATABASE IF EXISTS `3dgamedatalog`;
CREATE DATABASE `3dgamedatalog` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
