%%: 实现
-module(cfg_task_new_chs).
-compile(export_all).
-include("cfg_task_new.hrl").
-include("logger.hrl").

getRow(1)->
    #task_newCfg {
    id = 1,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 2,
    task_before = 0,
    target_para = #target_paraCfg {getnpc=1},
    task_name = "冒险的开始",
    task_content = "和luna女神交谈，开始你的冒险之旅。",
    task_epic_content = "史诗任务说明",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(2)->
    #task_newCfg {
    id = 2,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 3,
    task_before = 1,
    target_para = #target_paraCfg {getnpc=6},
    task_name = "居民身份登记",
    task_content = "登记注册成为蓝色大陆的一名勇敢的冒险者。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(3)->
    #task_newCfg {
    id = 3,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 4,
    task_before = 2,
    target_para = #target_paraCfg {getnpc=8},
    task_name = "获得武器",
    task_content = "赶紧去找铁匠，他为每一位新来的冒险者准备了全新的武器。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(4)->
    #task_newCfg {
    id = 4,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 17,
    task_after = 5,
    task_before = 3,
    target_para = #target_paraCfg {minicopy=401, mininpc=8, minishow=0},
    task_name = "勇气试炼",
    task_content = "拿起武器，击败面前的敌人。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(5)->
    #task_newCfg {
    id = 5,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 6,
    task_before = 4,
    target_para = #target_paraCfg {getnpc=10},
    task_name = "技能的意义",
    task_content = "向职业管理员询问关于技能的意义。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(6)->
    #task_newCfg {
    id = 6,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 7,
    task_before = 5,
    target_para = #target_paraCfg {getnpc=10},
    task_name = "第一个技能",
    task_content = "学习和装备第一个技能。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(7)->
    #task_newCfg {
    id = 7,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 17,
    task_after = 8,
    task_before = 6,
    target_para = #target_paraCfg {minicopy=402, mininpc=10, minishow=0},
    task_name = "技能的威力",
    task_content = "试试新技能的威力",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(8)->
    #task_newCfg {
    id = 8,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 9,
    task_before = 7,
    target_para = #target_paraCfg {getnpc=2},
    task_name = "农场主的烦恼",
    task_content = "据说农场主最近遇到了一些麻烦，去看看到底怎么回事。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(9)->
    #task_newCfg {
    id = 9,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 13,
    task_after = 10,
    task_before = 8,
    target_para = #target_paraCfg {citem=242, cnum=2, cobj=1, cmin=1, cmax=1},
    task_name = "追查",
    task_content = "为农场主采集不明生物留下的痕迹。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(10)->
    #task_newCfg {
    id = 10,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 11,
    task_before = 9,
    target_para = #target_paraCfg {getnpc=12},
    task_name = "原来是它？",
    task_content = "找魔法工会的人询问不明生物的信息",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(11)->
    #task_newCfg {
    id = 11,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 15,
    task_after = 12,
    task_before = 10,
    target_para = #target_paraCfg {ucontent="阿克勒香草", unum=1, uobj=2},
    task_name = "引诱史莱姆",
    task_content = "使用阿克勒香草，吸引史莱姆。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(12)->
    #task_newCfg {
    id = 12,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 17,
    task_after = 13,
    task_before = 11,
    target_para = #target_paraCfg {minicopy=403, mininpc=12, minishow=0},
    task_name = "清楚烦恼",
    task_content = "消灭这些来农场作乱的史莱姆。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(13)->
    #task_newCfg {
    id = 13,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 14,
    task_before = 12,
    target_para = #target_paraCfg {getnpc=1},
    task_name = "女神的担忧",
    task_content = "询问女神到底在担心什么？",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(14)->
    #task_newCfg {
    id = 14,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 15,
    task_before = 13,
    target_para = #target_paraCfg {getnpc=7},
    task_name = "骑士兵团的求助",
    task_content = "快去看看骑士兵团有什么需要帮助的？",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(15)->
    #task_newCfg {
    id = 15,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 13,
    task_after = 16,
    task_before = 14,
    target_para = #target_paraCfg {citem=243, cnum=2, cobj=3, cmin=1, cmax=1},
    task_name = "添加粮草",
    task_content = "骑士兵团需要大量的粮草，去搬运一些粮草回来。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(16)->
    #task_newCfg {
    id = 16,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 17,
    task_before = 15,
    target_para = #target_paraCfg {getnpc=9},
    task_name = "不翼而飞",
    task_content = "调查兵团粮草不翼而飞的原因。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(17)->
    #task_newCfg {
    id = 17,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 15,
    task_after = 18,
    task_before = 16,
    target_para = #target_paraCfg {ucontent="魔法照明弹", unum=1, uobj=5},
    task_name = "检查粮仓",
    task_content = "用照明弹监视兵团粮草。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(18)->
    #task_newCfg {
    id = 18,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 17,
    task_after = 19,
    task_before = 17,
    target_para = #target_paraCfg {minicopy=404, mininpc=7, minishow=0},
    task_name = "支援战斗",
    task_content = "帮助骑士兵团消灭那些偷盗粮草的盗贼。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 1,
    branch_is_pathfinding = 0
    };
getRow(19)->
    #task_newCfg {
    id = 19,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 20,
    task_before = 18,
    target_para = #target_paraCfg {getnpc=7},
    task_name = "追溯源头",
    task_content = "向兵团团长询问这些盗贼的情况。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 1,
    branch_is_pathfinding = 0
    };
getRow(20)->
    #task_newCfg {
    id = 20,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 21,
    task_before = 19,
    target_para = #target_paraCfg {getnpc=12},
    task_name = "魔法师的要求",
    task_content = "魔法工会的人需要一些蘑菇，这或许有着某些秘密。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(21)->
    #task_newCfg {
    id = 21,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 13,
    task_after = 22,
    task_before = 20,
    target_para = #target_paraCfg {citem=241, cnum=2, cobj=6, cmin=1, cmax=1},
    task_name = "采集样本",
    task_content = "采集一些毒蘑菇给魔法工会研究。",
    show_type1 = 0,
    show_type2 = 1,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(22)->
    #task_newCfg {
    id = 22,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 23,
    task_before = 21,
    target_para = #target_paraCfg {getnpc=12},
    task_name = "了解真相",
    task_content = "从魔法工会了解到事情的真相。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(23)->
    #task_newCfg {
    id = 23,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 24,
    task_before = 22,
    target_para = #target_paraCfg {getnpc=1},
    task_name = "汇报",
    task_content = "向女神汇报了解到的情况。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 1,
    branch_is_pathfinding = 0
    };
getRow(24)->
    #task_newCfg {
    id = 24,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 12,
    task_after = 25,
    task_before = 23,
    target_para = #target_paraCfg {getnpc=3},
    task_name = "出城许可",
    task_content = "去找猫绅士获得出城的许可证。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(25)->
    #task_newCfg {
    id = 25,
    tasktype = 0,
    maps = 1,
    groupid = 1,
    epic_task_groupid = 0,
    target_type = 16,
    task_after = 0,
    task_before = 24,
    target_para = #target_paraCfg {finishcopy=101},
    task_name = "激战蘑菇王",
    task_content = "清除这些该死的蘑菇。",
    show_type1 = 0,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50001)->
    #task_newCfg {
    id = 50001,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=2322},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50002)->
    #task_newCfg {
    id = 50002,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=2467},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50003)->
    #task_newCfg {
    id = 50003,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=2612},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50004)->
    #task_newCfg {
    id = 50004,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=2758},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50005)->
    #task_newCfg {
    id = 50005,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=2903},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50006)->
    #task_newCfg {
    id = 50006,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=3048},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50007)->
    #task_newCfg {
    id = 50007,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=3193},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50008)->
    #task_newCfg {
    id = 50008,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=3338},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50009)->
    #task_newCfg {
    id = 50009,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=3483},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50010)->
    #task_newCfg {
    id = 50010,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=3629},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50011)->
    #task_newCfg {
    id = 50011,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=3774},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50012)->
    #task_newCfg {
    id = 50012,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=3919},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50013)->
    #task_newCfg {
    id = 50013,
    tasktype = 1,
    maps = 5,
    groupid = 100,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=400, exp=4064},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50014)->
    #task_newCfg {
    id = 50014,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=3724},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50015)->
    #task_newCfg {
    id = 50015,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=3957},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50016)->
    #task_newCfg {
    id = 50016,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=4190},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50017)->
    #task_newCfg {
    id = 50017,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=4423},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50018)->
    #task_newCfg {
    id = 50018,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=4655},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50019)->
    #task_newCfg {
    id = 50019,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=4888},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50020)->
    #task_newCfg {
    id = 50020,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=5121},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50021)->
    #task_newCfg {
    id = 50021,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=5354},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50022)->
    #task_newCfg {
    id = 50022,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=5586},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50023)->
    #task_newCfg {
    id = 50023,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=5819},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50024)->
    #task_newCfg {
    id = 50024,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=6052},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50025)->
    #task_newCfg {
    id = 50025,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=600, exp=6285},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50026)->
    #task_newCfg {
    id = 50026,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=6518},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50027)->
    #task_newCfg {
    id = 50027,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=3724},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50028)->
    #task_newCfg {
    id = 50028,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=3957},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50029)->
    #task_newCfg {
    id = 50029,
    tasktype = 1,
    maps = 5,
    groupid = 101,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=4190},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50030)->
    #task_newCfg {
    id = 50030,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=6517},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50031)->
    #task_newCfg {
    id = 50031,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=6860},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50032)->
    #task_newCfg {
    id = 50032,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=7203},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50033)->
    #task_newCfg {
    id = 50033,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=7546},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50034)->
    #task_newCfg {
    id = 50034,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=7889},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50035)->
    #task_newCfg {
    id = 50035,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=8232},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50036)->
    #task_newCfg {
    id = 50036,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=8575},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50037)->
    #task_newCfg {
    id = 50037,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=8918},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50038)->
    #task_newCfg {
    id = 50038,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=9261},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50039)->
    #task_newCfg {
    id = 50039,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=9604},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50040)->
    #task_newCfg {
    id = 50040,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=5488},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50041)->
    #task_newCfg {
    id = 50041,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=5831},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50042)->
    #task_newCfg {
    id = 50042,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=6174},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50043)->
    #task_newCfg {
    id = 50043,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=6517},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50044)->
    #task_newCfg {
    id = 50044,
    tasktype = 1,
    maps = 5,
    groupid = 102,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=6860},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50045)->
    #task_newCfg {
    id = 50045,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=8802},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50046)->
    #task_newCfg {
    id = 50046,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=9221},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50047)->
    #task_newCfg {
    id = 50047,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=9640},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50048)->
    #task_newCfg {
    id = 50048,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=10059},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50049)->
    #task_newCfg {
    id = 50049,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=10479},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50050)->
    #task_newCfg {
    id = 50050,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=1300, exp=10898},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50051)->
    #task_newCfg {
    id = 50051,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=11317},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50052)->
    #task_newCfg {
    id = 50052,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=11736},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50053)->
    #task_newCfg {
    id = 50053,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=6706},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50054)->
    #task_newCfg {
    id = 50054,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=7125},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50055)->
    #task_newCfg {
    id = 50055,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=7544},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50056)->
    #task_newCfg {
    id = 50056,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=7964},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50057)->
    #task_newCfg {
    id = 50057,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=8383},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50058)->
    #task_newCfg {
    id = 50058,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=8802},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50059)->
    #task_newCfg {
    id = 50059,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=9221},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50060)->
    #task_newCfg {
    id = 50060,
    tasktype = 1,
    maps = 5,
    groupid = 103,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=9640},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50061)->
    #task_newCfg {
    id = 50061,
    tasktype = 1,
    maps = 5,
    groupid = 104,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=13671},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50062)->
    #task_newCfg {
    id = 50062,
    tasktype = 1,
    maps = 5,
    groupid = 104,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=14240},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50063)->
    #task_newCfg {
    id = 50063,
    tasktype = 1,
    maps = 5,
    groupid = 104,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=14810},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50064)->
    #task_newCfg {
    id = 50064,
    tasktype = 1,
    maps = 5,
    groupid = 104,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=15380},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50065)->
    #task_newCfg {
    id = 50065,
    tasktype = 1,
    maps = 5,
    groupid = 104,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=15949},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50066)->
    #task_newCfg {
    id = 50066,
    tasktype = 1,
    maps = 5,
    groupid = 104,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=9114},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50067)->
    #task_newCfg {
    id = 50067,
    tasktype = 1,
    maps = 5,
    groupid = 104,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=9683},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50068)->
    #task_newCfg {
    id = 50068,
    tasktype = 1,
    maps = 5,
    groupid = 104,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马游牧民",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马游牧民[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=10253},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50069)->
    #task_newCfg {
    id = 50069,
    tasktype = 1,
    maps = 5,
    groupid = 104,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马侦查兵",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马侦察兵[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=10823},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50070)->
    #task_newCfg {
    id = 50070,
    tasktype = 1,
    maps = 5,
    groupid = 104,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=11392},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50071)->
    #task_newCfg {
    id = 50071,
    tasktype = 1,
    maps = 5,
    groupid = 105,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=15262},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50072)->
    #task_newCfg {
    id = 50072,
    tasktype = 1,
    maps = 5,
    groupid = 105,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=15989},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50073)->
    #task_newCfg {
    id = 50073,
    tasktype = 1,
    maps = 5,
    groupid = 105,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭草原苍狼",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]草原苍狼[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=16716},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50074)->
    #task_newCfg {
    id = 50074,
    tasktype = 1,
    maps = 5,
    groupid = 105,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马勇士",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马勇士[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=17443},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(50075)->
    #task_newCfg {
    id = 50075,
    tasktype = 1,
    maps = 5,
    groupid = 105,
    epic_task_groupid = 0,
    target_type = 11,
    task_after = 0,
    task_before = 0,
    target_para = #target_paraCfg {mst=9016, mstnum=35},
    task_name = "剿灭半人马萨满",
    task_content = "接受到委托，前往[ff00ff]阿克勒平原[-]剿灭35只[ff00ff]半人马萨满[-]可领取丰厚的经验奖励！",
    task_reward_num = #task_reward_numCfg {gold=2800, exp=17443},
    show_type1 = 30054,
    show_type2 = 0,
    is_pathfinding = 0,
    branch_is_pathfinding = 0
    };
getRow(_)->[].

getKeyList()->[
    {1},
    {2},
    {3},
    {4},
    {5},
    {6},
    {7},
    {8},
    {9},
    {10},
    {11},
    {12},
    {13},
    {14},
    {15},
    {16},
    {17},
    {18},
    {19},
    {20},
    {21},
    {22},
    {23},
    {24},
    {25},
    {50001},
    {50002},
    {50003},
    {50004},
    {50005},
    {50006},
    {50007},
    {50008},
    {50009},
    {50010},
    {50011},
    {50012},
    {50013},
    {50014},
    {50015},
    {50016},
    {50017},
    {50018},
    {50019},
    {50020},
    {50021},
    {50022},
    {50023},
    {50024},
    {50025},
    {50026},
    {50027},
    {50028},
    {50029},
    {50030},
    {50031},
    {50032},
    {50033},
    {50034},
    {50035},
    {50036},
    {50037},
    {50038},
    {50039},
    {50040},
    {50041},
    {50042},
    {50043},
    {50044},
    {50045},
    {50046},
    {50047},
    {50048},
    {50049},
    {50050},
    {50051},
    {50052},
    {50053},
    {50054},
    {50055},
    {50056},
    {50057},
    {50058},
    {50059},
    {50060},
    {50061},
    {50062},
    {50063},
    {50064},
    {50065},
    {50066},
    {50067},
    {50068},
    {50069},
    {50070},
    {50071},
    {50072},
    {50073},
    {50074},
    {50075}
    ].

get1KeyList()->[
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    50001,
    50002,
    50003,
    50004,
    50005,
    50006,
    50007,
    50008,
    50009,
    50010,
    50011,
    50012,
    50013,
    50014,
    50015,
    50016,
    50017,
    50018,
    50019,
    50020,
    50021,
    50022,
    50023,
    50024,
    50025,
    50026,
    50027,
    50028,
    50029,
    50030,
    50031,
    50032,
    50033,
    50034,
    50035,
    50036,
    50037,
    50038,
    50039,
    50040,
    50041,
    50042,
    50043,
    50044,
    50045,
    50046,
    50047,
    50048,
    50049,
    50050,
    50051,
    50052,
    50053,
    50054,
    50055,
    50056,
    50057,
    50058,
    50059,
    50060,
    50061,
    50062,
    50063,
    50064,
    50065,
    50066,
    50067,
    50068,
    50069,
    50070,
    50071,
    50072,
    50073,
    50074,
    50075
    ].

